### ISSUE TITLE
HomePage Loading Circle

### ISSUE THREAD

**Issue by nunofmds** [linuxserver/docker-nextcloud#144]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Circle progress should disappear after work done

## Current Behavior
Circle progress always spinning

## Steps to Reproduce

1. Login and open homepage

## Environment
**OS: Debian   
**CPU architecture:** x86_64
**How docker service was installed:** Debian Package

## Docker logs

All details here https://github.com/nextcloud/text/issues/820
Maybe is necessary to adjust the default nginx config to remove thoose error_page...

**Comment by aptalca** [comment]
Thanks for the heads up, we'll update it.

**Comment by nunofmds** [comment]
Thanks...Please validate what's the best to do cause I don't know the impact on other stuff... for me commenting those lines fixed...

**Comment by aptalca** [comment]
Actually, those were removed well over a year ago, for Nextcloud v15: https://github.com/linuxserver/docker-nextcloud/commit/39fd8e322bf243ded22a6409e9323b75fd3d964f#diff-cab6a3a029fd4edc2e44acec10375bdcL44-L45

Our changelog includes notes about existing users having to delete the default site conf and restart the container to update whenever there is a new update pushed such as this one: `18.11.19: - Nginx default site config updated for v17 (existing users should delete /config/nginx/site-confs/default and restart the container).`
We don't automatically update it because that file is user customizable and we don't want to overwrite any user customizations
