### ISSUE TITLE
Extremely slow (90 sec) startup

### ISSUE THREAD

**Issue by ohthehugemanatee** [linuxserver/docker-nextcloud#181]
## Expected Behavior
Container should init to "ready" state, serving requests, in <30 seconds. 

## Current Behavior
The init scripts take 1.5 MINUTES to run through on any of my machines, with nextcloud codebase mounted, 8TB filestore on NFS, and remote database already installed.

## Steps to Reproduce

1. Prepare a large filestore, database, and nextcloud codebase
2. Start the container

## Environment
I run nextcloud in a kubernetes cluster. This is observed on a variety of node environments as follows:

**OS:** linux raspbian, ubuntu 20.04, manjaro-latest...
**CPU architecture:** x86_64/arm64
**How docker service was installed:**
Along with k3s.

## Command used to create docker container (run/create/compose/screenshot)

https://www.github.com/ohthehugemanatee/homenet-documentation/tree/master/cluster%2Fservices%2Fnextcloud.yaml

## Docker logs
All logs normal.

Watching logs in realtime, the longest stage by far is setting permissions.

Suggestion 1: look through init steps and consider what needs to be run in a blocking manner. e.g. `chown /data` can run in a subprocess, it doesn't have to block the rest of startup.

Suggestion 2: benchmark chown against `find -exec chown`. I suspect chown actually has to touch the ownership bits for every file, while find will use the kernel metadata cache.

**Comment by aptalca** [comment]
you're likely hitting the docker overlayfs bug that makes initial chown slow. There is no alternative or a fix. Hits devices randomly

**Comment by ohthehugemanatee** [comment]
Thanks for the fast response!

- what overlayfs bug? Can you link for more info please? I have a hard time imagining an overlayfs issue that would impact chowning an NFS mounted filesystem.
- if that is the case, suggestion 1 above would be a good mitigation.

**Comment by mikew** [comment]
Is the `chown` even necessary on every startup, for every user? It looks pretty simple to make it optional.

**Comment by techieshark** [comment]
@ohthehugemanatee perhaps https://github.com/docker/for-linux/issues/388 (mentioned here https://github.com/linuxserver/docker-bookstack/issues/60#issuecomment-712133695)

**Comment by techieshark** [comment]
There's a potential workaround, to speed things up, is based on suggestion from @ohthehugemanatee and [this comment](https://github.com/docker/for-linux/issues/388#issuecomment-685410250) mentioning using `find` and `xargs` (which only touches files it needs to). In my case it seems to make startup go from two minutes to about 10 seconds.

First, override the init script which is the source of the slowness: copy https://github.com/linuxserver/docker-nextcloud/blob/master/root/etc/cont-init.d/40-config to a local file on your host like `root/etc/cont-init.d/40-config`. 

Second, remove these lines:
```
# permissions
...
chown -R abc:abc  \
	/var/lib/nginx
```

and replace with:
```
find /var/lib/nginx \
    -not -group abc -not -user abc -print0 | xargs -P 0 -0 --no-run-if-empty chown --no-dereference abc:abc
```
above, the "-P 0" makes `xargs` use all the CPUs and the criteria to find makes it skip files that don't need permissions changed.

Third, make a `Dockerfile` for a custom image that overwrites that startup script:

```Dockerfile
FROM ghcr.io/linuxserver/nextcloud
COPY ./root/etc /etc
```

then build and use it
```
docker build -t nextcloud .
```

(Note, I actually had this issue with the linuxserver/nginx image rather than `nextcloud`, but came across this issue and figured the solution might be the same, so YMMV and hopefully this helps.)
