### ISSUE TITLE
updater.phar: executable file not found in $PATH

### ISSUE THREAD

**Issue by obbardc** [linuxserver/docker-nextcloud#208]
trying to update the release of Nextcloud inside the container results in:

```
$ docker exec -it nextcloud updater.phar --no-interaction
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "updater.phar": executable file not found in $PATH: unknown
```

**Comment by obbardc** [comment]
hm, seemed to work fine after the container started properly.

**Comment by gr33k** [comment]
If you are executing this on a bash script (like I was) - you are spot on with the root cause. It is happening because nextcloud docker instances are not yet fully up and running. All you need to do is add a "sleep" step in the bash script, for me:
`sleep 5`
was enough time to let Nextcloud start - and the command to work (you may need to increase it depending on load time for your server).

Thank you for the tip! When you said "worked fine AFTER the container started properly" - That gave me the idea :)

**Comment by obbardc** [comment]
ahhh sorry! Yeah, I added a sleep 60 in and it's been fine ever since :-)
