### ISSUE TITLE
[RECOMMENDED FIX] 504 Gateway Time-out / Upstream timed out (110: Operation timed out) while reading response header from upstream

### ISSUE THREAD

**Issue by Razva** [linuxserver/docker-nextcloud#211]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
NextCloud should install as expected on first run.

## Current Behavior
Installation fails. Browser is posting: `504 Gateway Time-out`. This is caused by the fact that the installation is very slow on some ARM devices so fastcgi/proxy times out.

## Steps to Reproduce
Try to install NextCloud on a low-end ARM device.

## Environment
**OS:** Debian 10
**CPU architecture:** arm64
**How docker service was installed:** From the distro's repo.
**Device:** Odroid HC4
**Extra OS info:**
- Linux version 5.11.0-odroid-arm64 (gcc-8 (Debian 8.3.0-6) 8.3.0, GNU ld (GNU Binutils for Debian) 2.31.1)  SMP PREEMPT Debian 5.11.18-202108050550~buster (2021-08-04)
- Docker version 18.09.1, build 4c52b90

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose.yml` file provided in the documentation.

## Docker logs
```
[error] 412#412: *14 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.11.12.1, server: _, request: "POST /index.php HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "cloud.rosca.info"
```

# Recommended fix
Modify the `config/nginx/site-confs/default` file as follows. The new lines should be added in the `location ~ \.php(?:$|/)` section:
```
fastcgi_read_timeout 600;
fastcgi_send_timeout 600;
fastcgi_connect_timeout 600;
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
```

# Confirmation
After making this change the installation got through without any issues.

**Comment by midiland** [comment]
Hello, I had the same problem, your fix works for me too.

Thank you.

**Comment by UNOPARATOR** [comment]
The recommened fix helped me with the 504 timeout when "Checking for system and security issues." in Administration --> Overview (/settings/ajax/checksetup).

**Comment by wonx** [comment]
Thank you, I couldn't download ISO files larger than 2-4GB from my server. This fixed my problem

**Comment by masterwishx** [comment]
Having this problem on Update Nextcloud 24.0.1

**Comment by myhrmans** [comment]
Same issue here, your fix worked.

**Comment by ryanrain2016** [comment]
Same issue here on 25.0.2, your fix worked.

**Comment by Leseratte10** [comment]
Still needed this fix with Nextcloud 25.0.3. Installation worked fine, but uploading larger files failed. 

Can this be included in the container?

**Comment by nemchik** [comment]
This is a very subjective change and can have negative effects in some cases. I would not want to include this in the package by default.

Our default shipped configurations follow the official nginx documented configurations for nginx reasonably closely: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html
There is also a page in their docs about large files that you may opt to review and adjust your configs depending on your needs: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

I'm going to close this and state that currently we do not plan to ship the above mentioned configs as defaults, but if there is a recommendation in nextcloud's docs in the future advising that this is needed for nextcloud to function or perform better it can be reconsidered.

**Comment by eyduh** [comment]
@nemchik I feel like this is a bug more so than a configuration preference.

I didn't used to get these fastcgi timeouts prior to updating to 25.0.2+, increasing the timeout window only makes them timeout later so it feels like something has changed in nextcloud that makes this container behind a reverse proxy timeout.

FYI I'm running this on a proxmox cluster of x86_64 servers and vms with gigabit connection between reverse proxy and the hypervisor that runs the nextcloud vm so it is not due to running on a low resource device.

I have increase the fpm workers as well as I saw a lot of trouble with that due to a lot of users having a lot of devices that all try to sync whenever the server is restarted. I don't think that the defaults should be changed necessarily but this seems to be something that props up every now and then with nextcloud updates, looking back through the nextcloud community forum.

**Comment by nemchik** [comment]
Just to clarify; one of the benefits of lower timeouts is to keep processes from occupying resources longer than they should. Configuring very high timeouts can make your system more vulnerable to DDoS or other types of attacks. Increasing timeouts can be necessary when applications expect to take longer times to complete necessary actions, or on lower powered devices to allow more time.

I am not saying "we will never change the defaults", but currently nextcloud does not document a need to do this in an out of the box installation (bare install, docker, proxy, or otherwise). I would prefer to defer to their guidance on shipping defaults. An exception would be where we find large amounts of the user base having issues with the shipped defaults, and a documented solution (for example nginx documentation, at least confirming that the changed values are justified to resolve a specific issue).

**Comment by eyduh** [comment]
I get it, I'm not saying you should or shouldn't change defaults - I'm saying that something in the image changed that is causing nginx to fail to connect to the php-fpm pool or workers on the same host, internally.

Even if I do set these ridiculously long timeouts, 90% of requests to the server timeout, whether a PROPFIND, GET, PUT, POST, MKOL, you name it. Leaving me with a very dysfunctional server. This suggests there might be an underlying issue that more than one user experience most likely between the current nginx version and the current implementation of php81-fpm.

Should I start a new issue to troubleshoot this?
