### ISSUE TITLE
LDAP Integration Not Functional 

### ISSUE THREAD

**Issue by MarkResearch** [linuxserver/docker-nextcloud#236]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Clean install of Nextcloud through unraid community app store, latest stable version php 7. Unable to use LDAP integration as buttons do not have any response. No errors on docker logs or Nextcloud logs level 2. Tested LDAP configuration on clean install of official Nextcloud docker image and Owncloud both worked smoothly. Clicking Test DN or save credentials does nothing. Unable to complete setup as continue button grayed out.

------------------------------

## Expected Behavior

Allow to enter and verify LDAP settings.

## Current Behavior

You can enter in the required info but clicking on any options does nothing.

## Steps to Reproduce
1. Enable LDAP/AD Integration app and attempt to enter info

## Environment
**OS: UNRAID
**CPU architecture: x64
**How docker service was installed: Preinstalled via unraid

## Command used to create docker container (run/create/compose/screenshot)
Using UNRAID community apps install

## Docker logs

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing...
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by chrisbley** [comment]
same issue here! is this issue going to be addressed? cheers for all the good work!

**Comment by BoavaNet** [comment]
ya having same issues here, damn was hopping to keep all my Authentication with LDAP

**Comment by NobleKangaroo** [comment]
Same issue here. This used to work in the past, but multiple folks have had issues related to routing ([1](https://github.com/nextcloud/server/issues/16194), [2](https://github.com/nextcloud/server/issues/23530), [3](https://github.com/nextcloud/server/issues/28704), [4](https://help.nextcloud.com/t/ldap-ad-authnetication-500-error-on-ajax-request/107168), [5](https://help.nextcloud.com/t/ldap-configuration-became-inaccessible-after-upgrade-to-21/121997)) since Nextcloud 20.0 released.

This looks to be related to a [PR for Nextcloud 19 to clean up and standardize the NGINX config and remove redundancy](https://github.com/nextcloud/documentation/pull/2197). However it was found that [the new config has issues with the legacy ajax endpoints of the user_ldap app](https://github.com/nextcloud/documentation/pull/2197#issuecomment-702530259). This line was subsequently reverted and added back to the NGINX config's documentation for 20.0 and later, and other projects such as NixOS [added the line to their configs](https://github.com/NixOS/nixpkgs/pull/101553/commits/b7a2a5f967a75bba3a39b709e0053b30b93779cd#diff-80ddb2d38f0f6e01125ccb8683381d7be20be1df3dce01e5c200dd74f5173623L578-R576).

Compared to the Nextcloud [19.0](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html) documentation for an NGINX setup (which the Linuxserver.io container uses), the Nextcloud [20.0](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) and [latest](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) documentation have the aforementioned line added to resolve issues with legacy AJAX endpoints:
```php
# Required for legacy support
rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;
```

This line is currently missing from this container's NGINX [config file](https://github.com/linuxserver/docker-nextcloud/blob/afc7a69cccdc3bd6acf2f9f49d64d34dfcbef600/root/defaults/default#L106) as it looks like #133 happened in January and February 2020 but Nextcloud 20.0 (which requires this extra line) came out in October 2020.

Adding that missing line results in the LDAP integration working again.

![image](https://user-images.githubusercontent.com/34781835/163241320-52dcb858-5c4e-486f-8a15-e4839bc4c755.png)

I'll fire up a PR to get this resolved.
