### ISSUE TITLE
[BUG] SMB in external storage doesn't work since the last update

### ISSUE THREAD

**Issue by stefore** [linuxserver/docker-nextcloud#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the 26.0.0-ls235 update, external storage does'nt work with SMB share :

`Undefined array key 1 at /config/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php#46`

It worked fine before.

### Steps To Reproduce

Try to mount a smb share in administration panel

### Environment

```markdown
- OS:Debian 10 buster
```

### CPU architecture

x86-64

### Docker creation

```bash
nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    env_file: ./0env_files/nextcloud.env
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    restart: unless-stopped
    depends_on:
      - mariadb
```

### Container logs

```bash
Undefined array key 1 at /config/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php#46
```

**Comment by ados1989** [comment]
Hello I have the same Problem. everything was fine but then I make the Update. Please help us.

**Comment by ados1989** [comment]
do you need more information ?

**Comment by TBhatti90** [comment]
Wanted to report I'm having the same issue. Someone mentioned on the nextcloud forums about downgrading libsmbclient, however, that may not necessarily fix it. Can you guys test that?
[Workaround](https://github.com/nextcloud/server/issues/36773)

**Comment by mixedracebaby** [comment]
All my smb connections died too

**Comment by j0nnymoe** [comment]
For now, please roll back the image tag until we get a chance to investigate.

**Comment by joem569** [comment]
I pulled my hair out for a little while until I came here to check the bug lists. I'm having the same issue. I rolled my image back to the previous version and it's working again. Will monitor to check the status!

**Comment by stefore** [comment]
the nextcloud:26.0.0-ls234 is the latest version with the SMB connections alive

**Comment by joem569** [comment]
> 26.0.0-ls234

Not that it needed to be confirmed, but I confirm this to be working currently!

**Comment by aptalca** [comment]
Changes between tags 234 and 235: https://github.com/linuxserver/docker-nextcloud/commit/85c15c72335b54f4415e82d5caec0104c1ecb64b

**Comment by 4rrior** [comment]
Can confirm it too.
I'm using as OS Unraid with Dockerimage from linuxserver: https://github.com/linuxserver/docker-nextcloud/pkgs/container/nextcloud
Current Version is: ls236
Shares worked with older versions.

I doesn't use Nextcloud for long time. So I removed the dockerimages of Nextcloud and Posgresql 15, include removing of all the stored data folders, to make a fresh clean new installation. Because I wanted to checkout, if some changes from updates break the installed external device app. But this was not the case, even then the Bug exists.

**Comment by Svenum** [comment]
Same here. Maybe related to: [https://github.com/nextcloud/server/issues/36773](https://github.com/nextcloud/server/issues/36773)

**Comment by nemchik** [comment]
From https://github.com/nextcloud/server/issues/36773#issuecomment-1495411432

> Notice:
> 
> * the cause of the problem is a **regression** in libsmbclient (samba) version 4.16.9 and 4.17.5
> * smbclient PHP extension is a victim of this, newly released version 1.1.0 is still affected
> * a possible **workaround** exists in [workaround for regression in libsmbclient 4.16.9/4.17.5 eduardok/libsmbclient-php#100](https://github.com/eduardok/libsmbclient-php/pull/100), you can try this [patch](https://patch-diff.githubusercontent.com/raw/eduardok/libsmbclient-php/pull/100.patch)

From https://github.com/linuxserver/docker-nextcloud/issues/303#issuecomment-1496038290

> Changes between tags 234 and 235: https://github.com/linuxserver/docker-nextcloud/commit/85c15c72335b54f4415e82d5caec0104c1ecb64b

Our build pipeline upgraded `libsmbclient` from `4.16.8-r1` (unaffected) to `4.16.10-r0` (problematic).

This could be fixed a number of ways:

1. The regression in `libsmbclient` could be fixed (and our build pipeline would release a new `-ls#` tagged version
2. Nextcloud could work around the regression in some way in a future release (and our build pipeline would release a new version of the image tagged for the updated version of Nextcloud, but this would still require following the update procedure in our readme)
3. We could make efforts to roll back `libsmbclient` to a working version

I would prefer to avoid option 3 but if the issue is not resolved somewhat soon we might go that route until option 1 or 2 are confirmed to have happened.

**Comment by stanthewizzard** [comment]
reverse to lscr.io/linuxserver/nextcloud:26.0.0-ls235
I still can't connect

**Comment by maximushugus** [comment]
For me 235 didnt work, I have to reverse to 234.
I also have another bug : apps on nextcloud (as onlyoffice, texte etc) can only open files in smb shares if the share is added as system (root) share. Here I can specify wich user can access what share but adding the share directly from user's interface make this bug

**Comment by Git-ChrisSc** [comment]
I have the same Problem on a fresh-installed Nextcloud:

libsmbclient 2:4.17.7+dfsg-1ubuntu2.3

Nextcloud 28.0.1

LXC Container under Proxmox  Running Ubuntu 23.04
Linux 5.15.116-1-pve x86_64

nginx/1.22.0
php 8.1.12

**Comment by j0nnymoe** [comment]
@Git-ChrisSc open a new issue.
