### ISSUE TITLE
Internal Server Error after upgrading to NC V27

### ISSUE THREAD

**Issue by squallxb1983** [linuxserver/docker-nextcloud#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After many attempts, I finally upgraded NC to V27, but now the login page says "Internal Server Error. The server was unable to complete your request."

The container log can be found below. Thank you for the help in advance.

### Steps To Reproduce

upgrade version of data from V21 to V27.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Stockholm
    volumes:
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/AppData/nextcloud/config:/config
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/Nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=998
      - PGID=100
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Stockholm
    volumes:
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/AppData/mariadb/config:/config
    restart: unless-stopped
```

### Container logs

```bash
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-20 │ 2023-06-24 │ /config/nginx/ssl.conf                                                 │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default
/config/nginx/site-confs/default.conf.bak
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by nemchik** [comment]
can you check the nextcloud log at `/data/nextcloud.log` ?

**Comment by squallxb1983** [comment]
> can you check the nextcloud log at `/data/nextcloud.log` ?

I deleted the log before Jun 24th and attached it as below. Thank you once again for the help.
[nextcloud.log](https://github.com/linuxserver/docker-nextcloud/files/12147936/nextcloud.log)

**Comment by nemchik** [comment]
Potential fix https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/830#issuecomment-1591070993

**Comment by squallxb1983** [comment]
> Potential fix [ONLYOFFICE/onlyoffice-nextcloud#830 (comment)](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/830#issuecomment-1591070993)

I'm not sure how to fix it. I tried removing onlyoffice and installing onlyoffice V8.1.0, but it seems neither worked for me.

**Comment by nemchik** [comment]
Can you try removing onlyoffice entirely and not installing another version and see if things run?

It could be a bug with onlyoffice that they need to fix. If things still don't run even when you remove onlyoffice entirely then it could be a bug on our end, or maybe still something else.

**Comment by Italia38** [comment]
Same problem here. Last update was 5/27 (v 26.02 I think). Updated today, and I'm getting the same message as @squallxb1983 
Running on an Alpine server (x86-64), Nextcloud and Mariadb installed and updated using docker-compose. 
I don't have the OnlyOffice App installed, so that is not my issue.

**Comment by nemchik** [comment]
Post your log. Even if it's the same error, there may be context around it.

**Comment by Italia38** [comment]
Here's the live log:
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-06-24 │ /config/nginx/ssl.conf                                                 │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /app/www/public/lib/private/DB/Connection.php:140
Stack trace:
#0 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect()
#1 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /app/www/public/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#3 /app/www/public/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /app/www/public/lib/private/DB/QueryBuilder/QueryBuilder.php(280): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /app/www/public/lib/private/AppConfig.php(418): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /app/www/public/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#7 /app/www/public/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#8 /app/www/public/lib/private/legacy/OC_App.php(803): OC\AppConfig->getValues()
#9 /app/www/public/lib/private/Server.php(733): OC_App::getAppVersions()
#10 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#11 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#13 /app/www/public/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#14 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#15 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#16 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#19 /app/www/public/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#20 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#21 /app/www/public/lib/private/Server.php(1115): OC\AppFramework\Utility\SimpleContainer->get()
#22 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#23 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#25 /app/www/public/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#26 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#27 /app/www/public/lib/private/Server.php(2067): OC\AppFramework\Utility\SimpleContainer->get()
#28 /app/www/public/lib/private/Files/View.php(106): OC\Server->getLockingProvider()
#29 /app/www/public/lib/private/Server.php(467): OC\Files\View->__construct()
#30 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#31 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#33 /app/www/public/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#34 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#35 /app/www/public/lib/private/Server.php(1469): OC\AppFramework\Utility\SimpleContainer->get()
#36 /app/www/public/lib/base.php(638): OC\Server->boot()
#37 /app/www/public/lib/base.php(1180): OC::init()
#38 /app/www/public/cron.php(43): require_once('...')
#39 {main}

**Comment by Italia38** [comment]
It appears to be a Mariadb error. Nextcloud can't connect to the database, per log above. I ran database check on Mariadb 
`mariadb-check -u root -p<PASSWORD> -c -A # check all databases for errors`
and got this:

mariadb-check: Got error: 2002: Can't connect to local server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect

I updated the Mariadb container at the same time as the Nextcloud update. Any pointers on how to fix Mariadb appreciated.

**Comment by Italia38** [comment]
Fixed the issue on my Nextcloud instance and was able to upgrade to v27. After fixing the Mariadb issue (see above) and pinning to v 10.6.13, Nextcloud appeared in Maintenance mode due to some database errors.  The fix was to change the line in the config file to turn maintenance mode off, then was able to log in to Nextcloud via the web interface. In Administration, ran checks and it showed database related errors, there were four outdated tables. Ran `docker exec -it nextcloud occ db:add-missing-indices`, then updated /nginx/site-confs/default.conf and  /nginx/nginx.conf, restarted the container, and all is updated and functioning properly so far.

**Comment by squallxb1983** [comment]
I gave up and installed nextcloud AIO instead. Then migrated all the data to AIO, now everything runs smoothly as it should be. The management in AIO is also easier and the new backup function is very useful.
