### ISSUE TITLE
[BUG] <Slow Uploads>

### ISSUE THREAD

**Issue by DemonAngeX2** [linuxserver/docker-nextcloud#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I upload a 4.5go file in 23 min (nextcloud estimation) but on dropbox, i upload it in 3min.

### Expected Behavior

The file should be upload at the same speed, on nextcloud or on dropbox.

### Steps To Reproduce

Drop and drop a file in nextcloud from Computer downloads(SSD) to nextcloud http WebUI

### Environment

```markdown
- OS:Unraid
- How docker service was installed: Native on Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
Can't send screenshot of my template ?
```

### Container logs

```bash
LSIO  

Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-20 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2023-03-21 │ 2023-06-23 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by DemonAngeX2** [comment]
![image](https://github.com/linuxserver/docker-nextcloud/assets/111583033/13c73312-efe0-4f14-9f8c-6d79bdcc9a9d)

**Comment by nemchik** [comment]
unRAID fuse layer (the part of unraid that makes `/mnt/user` work and put things in the right place) adds significant performance decrease. Try using a cache drive directly and see if the speeds are closer to what you expect.

**Comment by DemonAngeX2** [comment]
Hello, Tank you for your answer.

My /mnt/user is already in cache pool :/
![image](https://github.com/linuxserver/docker-nextcloud/assets/111583033/87980d4e-6d9f-447e-a0cc-17b82e49b567)

**Comment by nemchik** [comment]
> Hello, Tank you for your answer.
> 
> My /mnt/user is already in cache pool :/ ![image](https://user-images.githubusercontent.com/111583033/261821000-87980d4e-6d9f-447e-a0cc-17b82e49b567.png)

That's not the point though. unRAID makes your share available at `/mnt/user/appdata` or `/mnt/user/nextcloud` by creating a fuse filesystem. The fuse filesystem has performance overhead because it has to decide where to put the data (even if you configure unRAID to put data for that share only on a cache pool). What you need to do is directly use the disk mount such as `/mnt/cache/nextcloud` so that you're writing directly to the cache disk without using the unRAID share that has the fuse filesystem overhead.

I don't think the appdata volume is the concern by the way. You're trying to upload data to nextcloud, so it is probably the data mount you want to be writing directly to disk.

Depending on how you have that share setup, if you have the container write to the cache disk directly instead of the share, when unraid runs the mover to move things to your disk array nextcloud will no longer be able to see it. Because of this, I would recommend trying these settings only to test the performance. If the upload is fast while you are pointed directly at the disk rather than the share then it's the fuse filesystem overhead you're experiencing a problem with. That would be an unRAID issue you'd have to ask them for help with on their forum. If you still have slow uploads when writing directly to your disk (assuming your disk is an SSD) then it could be some other issue that could include settings for nextcloud or the container (or could also be some other unRAID specific issue).

So give it a try and let us know the results and we'll try to assist further.

**Comment by drizuid** [comment]
I can also assure you that dropbox's bandwidth, ISP peering, servers, disks, and literally everything else is significantly superior to your unraid box on a residential ISP connection.
It's been 3 weeks since 99's detailed post, so I will go ahead and close this.
