### ISSUE TITLE
[FEAT] Please provide tags for patches of previous major versions

### ISSUE THREAD

**Issue by HannesJo0139** [linuxserver/docker-nextcloud#433]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

One of the biggest problems of nextclouds development / release policies is that major releases come very often, introducing a bunch of new features and breaking existing ones. Over the years I learned that with nc it is a very bad idea to update a major relase too soon. I learned to have best experience always staying one major version behind the latest one.

As far as I understand https://github.com/linuxserver/docker-nextcloud/issues/420#issuecomment-2016831568 you not gonna provide a tag for 28.0.5 and coming 28.* since 29.0.0 is already available. So please would you consider providing tags for patch updates on earlier major versions? 

### Reason for change

..

**Comment by Roxedus** [comment]
Our current system does not allow for this.

**Comment by darkmattercoder** [comment]
@Roxedus can you elaborate on this? Or is that documented somewhere? Is this something that is scheduled for future change? Building tags for patches of at least one older version would be nice.

**Comment by Roxedus** [comment]
It is not documented further than the other issues about this. 
It is not scheduled to be looked at (this does not exclude it from being looked at, we have no official stance on this, other than the time investment it would take), mostly because this is a change that would only affect this single image (or a couple, I can't however name any that has this type of release cycle), and not the ~200 other images we build.
