### ISSUE TITLE
Image Tag Naming

### ISSUE THREAD

**Issue by muhlba91** [linuxserver/docker-nextcloud#75]
I have noticed since June this image is using the `latest` Nextcloud installation and that the published images are tagged using an incrementing number and it's also not easy at all to know which Nextcloud version has been used for which image in the end. This makes it very hard to distinguish between major version changes - and could lead to a possible break in existing installations.

What was the reason behind using `latest` and an incrementing number as the image's tag? Is it possible to restructure this to either build images with a certain release version or tag them correctly according to the version `latest` belongs to? Another option could be to keep `latest` with incrementing tags but add builds for explicit releases having a better tag name.

**Comment by j0nnymoe** [comment]
It shouldn't cause a break in existing installations. This is one of the few containers you need to update manually, but you need to make sure the image is updated first so that you have the correct dependencies in place. 

Using `latest` is just a docker thing and the numbering is for each weeks build. This is due to be reviewed soon once we look migrating this container over to our new pipeline setup.
