### ISSUE TITLE
NEXTCLOUD_VERSION missing

### ISSUE THREAD

**Issue by jodumont** [linuxserver/docker-nextcloud#95]
the [script-50](https://raw.githubusercontent.com/linuxserver/docker-nextcloud/master/root/etc/cont-init.d/50-install) looks for NEXTCLOUD_VERSION

which apparently suppose to be define in /version.txt

which is not in your [root dir](https://github.com/linuxserver/docker-nextcloud/tree/master/root)

![image](https://user-images.githubusercontent.com/5204724/55803946-abe8a900-5adb-11e9-9520-8e7e588f622f.png)

it seams to be already declared [here](https://github.com/linuxserver/docker-nextcloud/issues/23)

**Comment by jodumont** [comment]
@aptalca true cat /version.txt return 15.0.2
so I don't understand why shell and the script don't see this variable while it could return the PATH

**Comment by aptalca** [comment]
The line that's setting that variable is inside an if statement and if that statement is not true (when the nextcloud data already exists) the variable is never set.

**Comment by jodumont** [comment]
as a statement if it was true nextcloud would be installed than I would not open this issue ;)

**Comment by aptalca** [comment]
???

You're questioning the logic but you're missing half the bits. `version.txt` is not injected from the root folder in the git repo. It is generated via the Dockerfile during build time.

If you're having an issue with the install, tell us how it is not working, post a log, rather than going in circles about whether certain variables are set or not.
